### ISSUE TITLE
Incorrect formatting for recursively defined TS node definition

### ISSUE THREAD

**Issue by bbannier** [tweag/topiary#418]
It seems that `topiary::format` incorrectly formats recursively defined tree-sitter nodes, e.g., given a grammar

```js
module.exports = grammar({
	name: 'foo',

	rules: {
		foo: $ => seq(/FOO/, optional(seq('::', $.foo)))
	}
})
```

and an input `FOO::FOO` formatting without idempotency check produces `::FOO` instead of `FOO::FOO`. Since this construct is not allowed by the grammar this subsequently fails the idempotency check.

I believe this is a bug or limitation in topiary, but would be happy to know if I use it incorrectly.

* * *
Reproducer:

```toml
# Cargo.toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["macros", "rt"] }
topiary = { git = "https://github.com/tweag/topiary.git", rev = "8f790fc6b2a989850da3a7af5c30ab4a7e30c471" }
tree-sitter-facade = { git = "https://github.com/tweag/tree-sitter-facade" }
tree-sitter = "0.20.10"

[build-dependencies]
cc = "1.0.79"
```
```js
// grammar.js
module.exports = grammar({
	name: 'foo',

	rules: {
		foo: $ => seq(/FOO/, optional(seq('::', $.foo)))
	}
})
```
```rust
// build.rs
use {
    cc::Build,
    std::{
        env::{self, current_dir},
        path::PathBuf,
        process::Command,
    },
};

fn main() {
    let grammar = current_dir().unwrap().join("grammar.js");
    println!("cargo:rerun-if-changed=grammar.js");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Run `tree-sitter generate`.
    assert!(Command::new("tree-sitter")
        .arg("generate")
        .arg(&grammar)
        .current_dir(&out_dir)
        .status()
        .expect(
            "failed to generate tree-sitter bindings, is tree-sitter CLI installed and in PATH?"
        )
        .success());

    // Compile tree-sitter C output.
    let src_dir = out_dir.join("src");

    Build::new()
        .file(src_dir.join("parser.c"))
        .include(out_dir.join("src"))
        .warnings(false)
        .compile("tree-sitter-spicy");
}
```
```rust
// src/main.rs
extern "C" {
    fn tree_sitter_foo() -> tree_sitter::Language;
}

const QUERY: &'static str = "(#language! json)";
const INPUT: &'static str = "FOO::FOO";

fn main() {
    let grammars = [tree_sitter_facade::Language::from(unsafe {
        tree_sitter_foo()
    })];
    let configuration = topiary::Configuration::parse(QUERY).unwrap();

    let mut output = Vec::new();
    topiary::formatter(
        &mut INPUT.as_bytes(),
        &mut output,
        QUERY,
        &configuration,
        &grammars,
        topiary::Operation::Format {
            skip_idempotence: true,
        },
    )
    .unwrap();

    println!("{}", String::from_utf8(output).unwrap()); // Prints `::FOO` instead of `FOO::FOO`.
}
```
